/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Logica.Propietario;
import Logica.Vivienda;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de gestión de viviendas. Muestra la tabla de viviendas y permite
 * agregar, editar y eliminar.
 *
 * @author mario
 */
public class DlgGestionVivienda extends javax.swing.JDialog {

    private ArrayList<Vivienda> listaViviendas;
    private ArrayList<Propietario> listaPropietarios;
    private DefaultTableModel model;
    private java.awt.Frame padre;

    /**
     * Crea la ventana de gestión de viviendas.
     *
     * @param parent ventana padre
     * @param modal indica si la ventana es modal
     * @param listaViviendas lista de viviendas con la que trabaja
     * @param listaPropietarios lista de propietarios para asignar dueño
     */
    public DlgGestionVivienda(java.awt.Frame parent, boolean modal,
            ArrayList<Vivienda> listaViviendas,
            ArrayList<Propietario> listaPropietarios) {
        super(parent, modal);
        initComponents();
        this.padre = parent;
        this.listaViviendas = listaViviendas;
        this.listaPropietarios = listaPropietarios;
        muestraTabla();
    }

    public DlgGestionVivienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Llena la tabla con todas las viviendas de la lista.
     */
    private void muestraTabla() {
        String[] titulo = {"ID", "Descripción", "Dirección", "Mts Constr", "Mts Lote",
            "Tipo", "Cochera", "Habitac", "Baños", "Carretera",
            "Precio Base", "Depósito", "Propietario", "Estado"};
        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaViviendas.size(); i++) {
            Vivienda v = listaViviendas.get(i);
            Object[] row = {
                v.getIdVivienda(), v.getDescripcion(), v.getDireccion(),
                v.getMtsConstruc(), v.getMtsLote(), v.getTipoConstruccion(),
                v.isCochera() ? "Sí" : "No", v.getCantHabitac(), v.getCantBanios(),
                v.getCarretera(), v.getPrecioBase(), v.getDepositoGarantia(),
                v.getPropietario().getNomPropiet(), v.getEstado()
            };
            model.addRow(row);
        }
        tblViviendas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViviendas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblViviendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblViviendas);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar: ");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevaVivien.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la ventana para agregar una nueva vivienda y refresca la tabla.
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (listaPropietarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero debe registrar al menos un propietario");
            return;
        }
        DlgNewVivienda winNew = new DlgNewVivienda(padre, true, listaViviendas, listaPropietarios, 1);
        winNew.setVisible(true);
        this.listaViviendas = winNew.getListaViviendas();
        muestraTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Abre la ventana de edición de la vivienda seleccionada en la tabla.
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int index = tblViviendas.getSelectedRow();
        if (index >= 0) {
            Vivienda viv = listaViviendas.get(index);
            DlgNewVivienda winEdit = new DlgNewVivienda(padre, true, listaViviendas, listaPropietarios, 2, viv, index);
            winEdit.setVisible(true);
            this.listaViviendas = winEdit.getListaViviendas();
            muestraTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una vivienda");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Elimina la vivienda seleccionada en la tabla, previa confirmación.
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = tblViviendas.getSelectedRow();
        if (index >= 0) {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea borrar la vivienda seleccionada?");
            if (resp == JOptionPane.YES_OPTION) {
                listaViviendas.remove(index);
                JOptionPane.showMessageDialog(this, "Vivienda eliminada");
                muestraTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una vivienda");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Evento del cuadro de búsqueda; llama al filtrado.
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        filtrar();
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * Filtra la tabla mostrando solo las viviendas cuyo id coincide con lo
     * escrito.
     */
    private void filtrar() {
        String texto = txtBuscar.getText().toLowerCase();
        String[] titulo = {"ID", "Descripción", "Dirección", "Mts Constr", "Mts Lote",
            "Tipo", "Cochera", "Habitac", "Baños", "Carretera",
            "Precio Base", "Depósito", "Propietario", "Estado"};
        DefaultTableModel model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaViviendas.size(); i++) {
            Vivienda v = listaViviendas.get(i);
            String clave = String.valueOf(v.getIdVivienda());   // solo el ID
            if (clave.contains(texto)) {
                Object[] row = {
                    v.getIdVivienda(), v.getDescripcion(), v.getDireccion(),
                    v.getMtsConstruc(), v.getMtsLote(), v.getTipoConstruccion(),
                    v.isCochera() ? "Sí" : "No", v.getCantHabitac(), v.getCantBanios(),
                    v.getCarretera(), v.getPrecioBase(), v.getDepositoGarantia(),
                    v.getPropietario().getNomPropiet(), v.getEstado()
                };
                model.addRow(row);
            }
        }
        tblViviendas.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgGestionVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgGestionVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgGestionVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgGestionVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGestionVivienda dialog = new DlgGestionVivienda(
                        new javax.swing.JFrame(), true,
                        new java.util.ArrayList<>(),
                        new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViviendas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
