/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Logica.Inquilino;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de gestión de inquilinos. Muestra la tabla de inquilinos y permite
 * agregar, editar y eliminar.
 *
 * @author celeste
 */
public class DlgGestionInquilinos extends javax.swing.JDialog {

    /**
     * Creates new form DlgGestionInquilinos
     */
    private ArrayList<Inquilino> listaInquilinos;
    private DefaultTableModel model;
    private java.awt.Frame padre;

    /**
     * Crea la ventana de gestión de inquilinos.
     *
     * @param parent ventana padre
     * @param modal indica si la ventana es modal
     * @param listaInquilinos lista de inquilinos con la que trabaja
     */
    public DlgGestionInquilinos(java.awt.Frame parent, boolean modal,
            ArrayList<Inquilino> listaInquilinos) {
        super(parent, modal);
        initComponents();
        this.padre = parent;
        this.listaInquilinos = listaInquilinos;
        muestraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInquilinos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar: ");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevoInqui.png"))); // NOI18N
        btnAgregar.setText("Nuevo");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        tblInquilinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInquilinos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Llena la tabla con todos los inquilinos de la lista.
     */
    private void muestraTabla() {
        String[] titulo = {"Cedula", "Nombre", "Género", "Fecha Nac",
            "Dirección", "Teléfono", "Email", "Ocupacion"};
        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaInquilinos.size(); i++) {
            Object[] row = {
                listaInquilinos.get(i).getCedula(),
                listaInquilinos.get(i).getNombre(),
                listaInquilinos.get(i).getGenero(),
                listaInquilinos.get(i).getFechNac(),
                listaInquilinos.get(i).getDireccion(),
                listaInquilinos.get(i).getTelefono(),
                listaInquilinos.get(i).getEmail(),
                listaInquilinos.get(i).getOcupacion()
            };
            model.addRow(row);
        }
        tblInquilinos.setModel(model);
    }

    /**
     * Abre la ventana para agregar un nuevo inquilino y refresca la tabla.
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DlgNewInquilino winNew = new DlgNewInquilino(padre, true, listaInquilinos, 1);
        winNew.setVisible(true);
        this.listaInquilinos = winNew.getListaInquilinos();
        muestraTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Abre la ventana de edición del inquilino seleccionado en la tabla.
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int index = tblInquilinos.getSelectedRow();
        if (index >= 0) {
            Inquilino inq = listaInquilinos.get(index);
            DlgNewInquilino winEdit = new DlgNewInquilino(padre, true, listaInquilinos, 2, inq, index);
            winEdit.setVisible(true);
            this.listaInquilinos = winEdit.getListaInquilinos();
            muestraTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un inquilino");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Elimina el inquilino seleccionado en la tabla, previa confirmación.
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int index = tblInquilinos.getSelectedRow();
        if (index >= 0) {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea borrar el inquilino seleccionado?");
            if (resp == JOptionPane.YES_OPTION) {
                listaInquilinos.remove(index);
                JOptionPane.showMessageDialog(this, "Inquilino eliminado");
                muestraTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un inquilino");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Evento del cuadro de búsqueda; llama al filtrado.
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        filtrar();
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * Filtra la tabla mostrando solo los inquilinos cuya cédula coincide con lo
     * escrito.
     */
    private void filtrar() {
        String texto = txtBuscar.getText().toLowerCase();
        String[] titulo = {"Cedula", "Nombre", "Género", "Fecha Nac",
            "Dirección", "Teléfono", "Email", "Ocupación"};
        DefaultTableModel model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaInquilinos.size(); i++) {
            Inquilino inq = listaInquilinos.get(i);
            String clave = String.valueOf(inq.getCedula());   // solo la cédula
            if (clave.contains(texto)) {
                Object[] row = {
                    inq.getCedula(), inq.getNombre(), inq.getGenero(),
                    inq.getFechNac(), inq.getDireccion(), inq.getTelefono(),
                    inq.getEmail(), inq.getOcupacion()
                };
                model.addRow(row);
            }
        }
        tblInquilinos.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGestionInquilinos dialog = new DlgGestionInquilinos(
                        new javax.swing.JFrame(), true,
                        new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInquilinos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
