/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Logica.Mensualidades;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class DlgMensualidades extends javax.swing.JDialog {

    private ArrayList<Mensualidades> listaMensualidades;
    private ArrayList<Alquileres> listaAlquileres;
    private ArrayList<Inquilino> listaInquilinos;
    private DefaultTableModel model;

    /**
     * Creates new form DlgMensualidades
     */
    public DlgMensualidades(java.awt.Frame parent, boolean modal,
            ArrayList<Mensualidades> listaMensualidades,
            ArrayList<Alquileres> listaAlquileres,
            ArrayList<Inquilino> listaInquilinos) {
        super(parent, modal);
        initComponents();
        this.listaMensualidades = listaMensualidades;
        this.listaAlquileres = listaAlquileres;
        this.listaInquilinos = listaInquilinos;
        lblFechaActual.setText(LocalDate.now().toString());  // fecha del sistema
        muestraTabla();
    }

    public DlgMensualidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.listaMensualidades = new ArrayList<>();
        this.listaAlquileres = new ArrayList<>();
        this.listaInquilinos = new ArrayList<>();

        lblFechaActual.setText(LocalDate.now().toString());
        muestraTabla();
    }

    private int generarConsecutivo() {
        int max = 0;
        for (Mensualidades m : listaMensualidades) {
            if (m.getConsecutivo() > max) {
                max = m.getConsecutivo();
            }
        }
        return max + 1;
    }

    private double obtenerDescuento(int mes) {
        if (mes == 8 || mes == 9 || mes == 10) {   // Baja: Ago, Set, Oct
            return 0.10;
        }
        if (mes >= 3 && mes <= 7) {                 // Media: Mar a Jul
            return 0.05;
        }
        return 0.0;                                 // Alta: Nov, Dic, Ene, Feb
    }

    private String buscarNombreInquilino(int ced) {
        for (Inquilino i : listaInquilinos) {
            if (i.getCedInqui() == ced) {
                return i.getNomInqui();
            }
        }
        return "";
    }

    private boolean yaExisteMensualidad(int numAlquiler, int mes, int anio) {
        for (Mensualidades m : listaMensualidades) {
            if (m.getNumAlquiler() == numAlquiler
                    && m.getMesCobro() == mes
                    && m.getAnioActual() == anio) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFechaActual = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensualidades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFechaActual.setText("Fecha");

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaActual)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblMensualidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMensualidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (txtAnio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe indicar el año");
            return;
        }
        int anio;
        try {
            anio = Integer.parseInt(txtAnio.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser numerico");
            return;
        }
        int mes = cmbMes.getSelectedIndex() + 1;

        LocalDate hoy = LocalDate.now();
        LocalDate elegido = LocalDate.of(anio, mes, 1);
        LocalDate mesActual = LocalDate.of(hoy.getYear(), hoy.getMonthValue(), 1);
        if (elegido.isBefore(mesActual)) {
            JOptionPane.showMessageDialog(this, "No se puede generar para una fecha anterior a la actual");
            return;
        }

        int generados = 0;
        for (Alquileres a : listaAlquileres) {
            if (a.getEstado().equalsIgnoreCase("Vigente")) {
                if (yaExisteMensualidad(a.getNumAlquiler(), mes, anio)) {
                    continue;                                          // ya tiene ese mes/año
                }
                double porcDesc = obtenerDescuento(mes);
                double montoDescuento = a.getPrecioAlquiler() * porcDesc;
                double montoMes = a.getPrecioAlquiler() - montoDescuento;

                Mensualidades m = new Mensualidades(
                        generarConsecutivo(),
                        a.getNumAlquiler(),
                        LocalDate.now(),
                        buscarNombreInquilino(a.getCedInquilino()),
                        mes,
                        anio,
                        montoDescuento,
                        montoMes,
                        "Pendiente"
                );
                listaMensualidades.add(m);
                generados++;
            }
        }

        if (generados == 0) {
            JOptionPane.showMessageDialog(this, "No se generaron recibos (ya existían o no hay alquileres vigentes)");
        } else {
            JOptionPane.showMessageDialog(this, generados + " mensualidad(es) generada(s)");
        }
        muestraTabla();

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void muestraTabla() {
        String[] titulo = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino",
            "Mes", "Año", "Descuento", "Monto a Pagar", "Estado"};
        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaMensualidades.size(); i++) {
            Mensualidades m = listaMensualidades.get(i);
            Object[] row = {
                m.getConsecutivo(), m.getNumAlquiler(), m.getFechCreacion(),
                m.getNomInquilino(), m.getMesCobro(), m.getAnioActual(),
                m.getDescuento(), m.getMontoMes(), m.getEstado()
            };
            model.addRow(row);
        }
        tblMensualidades.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMensualidades dialog = new DlgMensualidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JTable tblMensualidades;
    private javax.swing.JTextField txtAnio;
    // End of variables declaration//GEN-END:variables
}
