/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Logica.Alquileres;
import Logica.Inquilino;
import Logica.Mensualidades;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class DlgMensualidades extends javax.swing.JDialog {

    private ArrayList<Mensualidades> listaMensualidades;
    private ArrayList<Alquileres> listaAlquileres;
    private ArrayList<Inquilino> listaInquilinos;
    private DefaultTableModel model;

    /**
     * Creates new form DlgMensualidades
     */
    public DlgMensualidades(java.awt.Frame parent, boolean modal,
            ArrayList<Mensualidades> listaMensualidades,
            ArrayList<Alquileres> listaAlquileres,
            ArrayList<Inquilino> listaInquilinos) {
        super(parent, modal);
        initComponents();
        this.listaMensualidades = listaMensualidades;
        this.listaAlquileres = listaAlquileres;
        this.listaInquilinos = listaInquilinos;
        txtFecha.setText(LocalDate.now().toString());   // fecha del sistema
        muestraTabla();
    }

    public DlgMensualidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.listaMensualidades = new ArrayList<>();
        this.listaAlquileres = new ArrayList<>();
        this.listaInquilinos = new ArrayList<>();

        lblFechaActual.setText(LocalDate.now().toString());
        muestraTabla();
    }

    private int generarConsecutivo() {
        int max = 0;
        for (Mensualidades m : listaMensualidades) {
            if (m.getConsecutivo() > max) {
                max = m.getConsecutivo();
            }
        }
        return max + 1;
    }

    private double obtenerDescuento(int mes) {
        if (mes == 8 || mes == 9 || mes == 10) {   // Baja: Ago, Set, Oct
            return 0.10;
        }
        if (mes >= 3 && mes <= 7) {                 // Media: Mar a Jul
            return 0.05;
        }
        return 0.0;                                 // Alta: Nov, Dic, Ene, Feb
    }

    private String buscarNombreInquilino(int ced) {
        for (Inquilino i : listaInquilinos) {
            if (i.getCedula() == ced) {
                return i.getNombre();
            }
        }
        return "";
    }

    private boolean yaExisteMensualidad(int numAlquiler, int mes, int anio) {
        for (Mensualidades m : listaMensualidades) {
            if (m.getNumAlquiler() == numAlquiler
                    && m.getMesCobro() == mes
                    && m.getAnioActual() == anio) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensualidades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblFechaActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbMesGenerar = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAnioGenerar = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbMesMostrar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAnioMostrar = new javax.swing.JTextField();
        btnGenerarMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Mensualidades");

        tblMensualidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMensualidades);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Mensualidades"));

        lblFechaActual.setText("Fecha Actual");

        jLabel1.setText("Mes");

        cmbMesGenerar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel2.setText("año");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaActual)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMesGenerar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFecha)
                    .addComponent(txtAnioGenerar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnGenerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaActual)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMesGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAnioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar Mensualidades"));

        jLabel3.setText("Mes");

        cmbMesMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel4.setText("año");

        btnGenerarMostrar.setText("Generar");
        btnGenerarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnGenerarMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addComponent(btnGenerarMostrar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (txtAnioGenerar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe indicar el año");
            return;
        }
        int anio;
        try {
            anio = Integer.parseInt(txtAnioGenerar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser numerico");
            return;
        }
        int mes = cmbMesGenerar.getSelectedIndex() + 1;

        LocalDate hoy = LocalDate.now();
        LocalDate elegido = LocalDate.of(anio, mes, 1);
        LocalDate mesActual = LocalDate.of(hoy.getYear(), hoy.getMonthValue(), 1);
        if (elegido.isBefore(mesActual)) {
            JOptionPane.showMessageDialog(this, "No se puede generar para una fecha anterior a la actual");
            return;
        }
        int generados = 0;
        for (Alquileres a : listaAlquileres) {
            if (a.getEstado().equalsIgnoreCase("Vigente")) {
                if (yaExisteMensualidad(a.getNumAlquiler(), mes, anio)) {
                    continue;
                }
                double porcDesc = obtenerDescuento(mes);
                double montoDescuento = a.getPrecioAlquiler() * porcDesc;
                double montoMes = a.getPrecioAlquiler() - montoDescuento;

                Mensualidades m = new Mensualidades(
                        generarConsecutivo(),
                        a.getNumAlquiler(),
                        LocalDate.now(),
                        buscarNombreInquilino(a.getCedInquilino()),
                        mes,
                        anio,
                        montoDescuento,
                        montoMes,
                        "Pendiente"
                );
                listaMensualidades.add(m);
                generados++;
            }
        }
        if (generados == 0) {
            JOptionPane.showMessageDialog(this, "No se generaron recibos (ya existían o no hay alquileres vigentes)");
        } else {
            JOptionPane.showMessageDialog(this, generados + " mensualidad(es) generada(s)");
        }
        muestraTabla();

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnGenerarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMostrarActionPerformed
        if (txtAnioMostrar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe indicar el año");
            return;
        }
        int anio;
        try {
            anio = Integer.parseInt(txtAnioMostrar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser numerico");
            return;
        }
        int mes = cmbMesMostrar.getSelectedIndex() + 1;

        String[] titulo = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino",
            "Mes", "Año", "Descuento", "Monto a Pagar", "Estado"};
        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaMensualidades.size(); i++) {
            Mensualidades m = listaMensualidades.get(i);
            if (m.getMesCobro() == mes && m.getAnioActual() == anio) {
                Object[] row = {
                    m.getConsecutivo(), m.getNumAlquiler(), m.getFechCreacion(),
                    m.getNomInquilino(), m.getMesCobro(), m.getAnioActual(),
                    m.getDescuento(), m.getMontoMes(), m.getEstado()
                };
                model.addRow(row);
            }
        }
        tblMensualidades.setModel(model);
    }//GEN-LAST:event_btnGenerarMostrarActionPerformed

    private void muestraTabla() {
        String[] titulo = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino",
            "Mes", "Año", "Descuento", "Monto a Pagar", "Estado"};
        model = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaMensualidades.size(); i++) {
            Mensualidades m = listaMensualidades.get(i);
            Object[] row = {
                m.getConsecutivo(), m.getNumAlquiler(), m.getFechCreacion(),
                m.getNomInquilino(), m.getMesCobro(), m.getAnioActual(),
                m.getDescuento(), m.getMontoMes(), m.getEstado()
            };
            model.addRow(row);
        }
        tblMensualidades.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMensualidades dialog = new DlgMensualidades(
                        new javax.swing.JFrame(), true,
                        new java.util.ArrayList<>(),
                        new java.util.ArrayList<>(),
                        new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGenerarMostrar;
    private javax.swing.JComboBox<String> cmbMesGenerar;
    private javax.swing.JComboBox<String> cmbMesMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JTable tblMensualidades;
    private javax.swing.JTextField txtAnioGenerar;
    private javax.swing.JTextField txtAnioMostrar;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
