/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Logica.Alquileres;
import Logica.Inquilino;
import Logica.Mensualidades;
import Logica.Propietario;
import Logica.Vivienda;
import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class FrmFormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmFormularioPrincipal
     */
    
    ArrayList<Propietario>   listaPropietarios   = new ArrayList<>();
    ArrayList<Inquilino>     listaInquilinos     = new ArrayList<>();
    ArrayList<Vivienda>      listaViviendas      = new ArrayList<>();
    ArrayList<Alquileres>    listaAlquileres     = new ArrayList<>();
    ArrayList<Mensualidades> listaMensualidades  = new ArrayList<>();
    
    
    
    public FrmFormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPropietarios = new javax.swing.JButton();
        btnViviendas = new javax.swing.JButton();
        btnAlquileres = new javax.swing.JButton();
        btnGanancias = new javax.swing.JButton();
        btnMensualidades = new javax.swing.JButton();
        btnInquilinos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Alquileres GuanaRent");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnPropietarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/propietario.png"))); // NOI18N
        btnPropietarios.setText("Propietarios");
        btnPropietarios.setHideActionText(true);
        btnPropietarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietariosActionPerformed(evt);
            }
        });

        btnViviendas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViviendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/propiedad.png"))); // NOI18N
        btnViviendas.setText("Viviendas");
        btnViviendas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnViviendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViviendasActionPerformed(evt);
            }
        });

        btnAlquileres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlquileres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/alquiler.png"))); // NOI18N
        btnAlquileres.setText("Alquileres");
        btnAlquileres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquileresActionPerformed(evt);
            }
        });

        btnGanancias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ganancias.png"))); // NOI18N
        btnGanancias.setText("Ganancias");
        btnGanancias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        btnMensualidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMensualidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mensualidad.png"))); // NOI18N
        btnMensualidades.setText("Mensualidades");
        btnMensualidades.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualidadesActionPerformed(evt);
            }
        });

        btnInquilinos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInquilinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/inquilino.png"))); // NOI18N
        btnInquilinos.setText("Inquilinos");
        btnInquilinos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInquilinosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViviendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInquilinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMensualidades))
                    .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnPropietarios)
                .addGap(18, 18, 18)
                .addComponent(btnViviendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMensualidades, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/imagenAlquiler.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jMenu1.setText("Gestion");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sistema");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietariosActionPerformed
        DlgGestionPropietarios win = new DlgGestionPropietarios(this, false, listaPropietarios);
    win.setVisible(true);
    }//GEN-LAST:event_btnPropietariosActionPerformed

    private void btnViviendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViviendasActionPerformed
        DlgGestionVivienda win = new DlgGestionVivienda(this, false, listaViviendas, listaPropietarios);
    win.setVisible(true);
    }//GEN-LAST:event_btnViviendasActionPerformed

    private void btnInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInquilinosActionPerformed
        DlgGestionInquilinos win = new DlgGestionInquilinos(this, false, listaInquilinos);
        win.setVisible(true);
    }//GEN-LAST:event_btnInquilinosActionPerformed

    private void btnAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquileresActionPerformed
          DlgGestionAlquileres win = new DlgGestionAlquileres(this, false,
            listaAlquileres, listaInquilinos, listaViviendas);
    win.setVisible(true);
    }//GEN-LAST:event_btnAlquileresActionPerformed

    private void btnMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualidadesActionPerformed
         DlgMensualidades win = new DlgMensualidades(this, false,
         listaMensualidades, listaAlquileres, listaInquilinos);
         win.setVisible(true);
    }//GEN-LAST:event_btnMensualidadesActionPerformed

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
         javax.swing.JOptionPane.showMessageDialog(this, "Módulo Ganancias - en construcción");
    }//GEN-LAST:event_btnGananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquileres;
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnInquilinos;
    private javax.swing.JButton btnMensualidades;
    private javax.swing.JButton btnPropietarios;
    private javax.swing.JButton btnViviendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
